DROP TABLESPACE ESADAT INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE ESAIDX INCLUDING CONTENTS AND DATAFILES;


CREATE TABLESPACE ESADAT 
    DATAFILE 'esadat_001.dtf' SIZE 10G ,
    'esadat_002.tbf' SIZE 10G 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;


CREATE TABLESPACE ESAIDX 
    DATAFILE 'esaidx_001.dtf' SIZE 1G REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 5G
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE; 

