echo ====================================================
echo export TB_SID=tac1
echo
echo tbboot nomount
echo
echo tbsql sys/tibero@tac1
echo
echo CREATE DATABASE
echo USER sys IDENTIFIED BY tibero
echo MAXDATAFILES 2048
echo CHARACTER SET UTF8 -- UTF8, EUCKR, ASCII
echo NATIONAL CHARACTER SET UTF16
echo LOGFILE
echo GROUP 0 \(\'+DS0/tac/redo/log01.log\'\) SIZE 50M,
echo GROUP 1 \(\'+DS0/tac/redo/log02.log\'\) SIZE 50M,
echo GROUP 2 \(\'+DS0/tac/redo/log03.log\'\) SIZE 50M
echo MAXLOGFILES 100
echo MAXLOGMEMBERS 8
echo NOARCHIVELOG
echo DATAFILE \'+DS0/tac/datafile/system001.dtf\' SIZE 200M
echo AUTOEXTEND ON NEXT 10M MAXSIZE 1G
echo DEFAULT TABLESPACE USR
echo DATAFILE \'+DS0/tac/datafile/usr001.dtf\' SIZE 100M
echo AUTOEXTEND ON NEXT 10M MAXSIZE 1G
echo DEFAULT TEMPORARY TABLESPACE TEMP
echo TEMPFILE \'+DS0/tac/datafile/temp001.dtf\' SIZE 200M
echo AUTOEXTEND ON NEXT 10M MAXSIZE 1G
echo EXTENT MANAGEMENT LOCAL AUTOALLOCATE
echo UNDO TABLESPACE UNDO0
echo DATAFILE \'+DS0/tac/datafile/undo0.dtf\' SIZE 200M
echo AUTOEXTEND ON NEXT 10M MAXSIZE 1G
echo EXTENT MANAGEMENT LOCAL AUTOALLOCATE \;
echo ====================================================
echo 

export TB_SID=tac1
tbboot nomount
tbsql sys/tibero@tac1 <<EOF

CREATE DATABASE
USER sys IDENTIFIED BY tibero
MAXDATAFILES 2048
CHARACTER SET UTF8 -- UTF8, EUCKR, ASCII
NATIONAL CHARACTER SET UTF16
LOGFILE
GROUP 0 ('+DS0/tac/redo/log01.log') SIZE 50M,
GROUP 1 ('+DS0/tac/redo/log02.log') SIZE 50M,
GROUP 2 ('+DS0/tac/redo/log03.log') SIZE 50M
MAXLOGFILES 100
MAXLOGMEMBERS 8
NOARCHIVELOG
DATAFILE '+DS0/tac/datafile/system001.dtf' SIZE 200M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G
DEFAULT TABLESPACE USR
DATAFILE '+DS0/tac/datafile/usr001.dtf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G
DEFAULT TEMPORARY TABLESPACE TEMP
TEMPFILE '+DS0/tac/datafile/temp001.dtf' SIZE 200M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
UNDO TABLESPACE UNDO0
DATAFILE '+DS0/tac/datafile/undo0.dtf' SIZE 200M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL AUTOALLOCATE ;

quit
EOF
