CREATE TABLE PERFORMANCE_SERVER (
	DATE_DAY VARCHAR(15) NOT NULL,
	DATE_HMS VARCHAR(15) NOT NULL,
	DATE_WEEK INT NOT NULL,
	CPU_USED FLOAT NOT NULL,
	CPU_LOAD FLOAT NOT NULL,
	IO_WAIT FLOAT NOT NULL,
	MEM_TOTAL FLOAT NOT NULL,
	MEM_USED FLOAT NOT NULL,
	MEM_FREE FLOAT NOT NULL,
	MEM_CALC FLOAT NOT NULL,
	MEM_SWAP_TOTAL FLOAT NOT NULL,
	MEM_SWAP_USED FLOAT NOT NULL,
	MEM_SWAP_FREE FLOAT NOT NULL,
	MEM_SWAP_CALC FLOAT NOT NULL,
	DB_BUFFER_HIT FLOAT NOT NULL,
	DB_TEMP_USED FLOAT NOT NULL,
	BROKER_PID INT NOT NULL,
	BROKER_AS INT NOT NULL,
	BROKER_JQ INT NOT NULL,
	BROKER_TPS INT NOT NULL,
	BROKER_QPS INT NOT NULL,
	BROKER_SELECT INT NOT NULL,
	BROKER_INSERT INT NOT NULL,
	BROKER_UPDATE INT NOT NULL,
	BROKER_DELETE INT NOT NULL,
	BROKER_OTHERS INT NOT NULL,
	BROKER_LONGT INT NOT NULL,
	BROKER_LONGQ INT NOT NULL,
	BROKER_ERRQ INT NOT NULL,
	BROKER_CONNECT INT NOT NULL,
	BROKER_REJECT INT NOT NULL,
	BROKER_BUSY INT NOT NULL,
	CONSTRAINT pk_performance_server_date_day_date_hms PRIMARY KEY(DATE_DAY, DATE_HMS)
) REUSE_OID;

CREATE TABLE PERFORMANCE_PROCESS (
	DATE_DAY VARCHAR(15) NOT NULL,
	DATE_HMS VARCHAR(15) NOT NULL,
	DATE_WEEK INT NOT NULL,
	CUB_PID VARCHAR(15) NOT NULL,
	CUB_CPU_USED VARCHAR(15) NOT NULL,
	CUB_MEM_USED VARCHAR(15) NOT NULL,
	CONSTRAINT pk_performance_process_date_day_date_hms PRIMARY KEY(DATE_DAY, DATE_HMS)
)REUSE_OID;

CREATE TABLE PERFORMANCE_VOLUME (
	DATE_DAY VARCHAR(15) NOT NULL,
	DATE_HMS VARCHAR(15) NOT NULL,
	DATE_WEEK INT NOT NULL,
	VOL_TYPE VARCHAR(10) NOT NULL,
	TOT_SIZE FLOAT NOT NULL,
	USED_SIZE FLOAT NOT NULL,
	FREE_SIZE FLOAT NOT NULL,
	CONSTRAINT pk_performance_volume_date_day_date_hms_vol_type PRIMARY KEY(DATE_DAY, DATE_HMS, VOL_TYPE)
)REUSE_OID;

CREATE TABLE PERFORMANCE_DISK (
	DATE_DAY VARCHAR(15) NOT NULL,
	DATE_HMS VARCHAR(15) NOT NULL,
	DATE_WEEK INT NOT NULL,
	DB_MODE VARCHAR(5) NOT NULL,
	"DATA_TYPE" VARCHAR(7) NOT NULL,
	DATA_PATH VARCHAR(20) NOT NULL,
	DISK_TOT_SIZE INT NOT NULL,
	DISK_USED_SIZE INT NOT NULL,
	DISK_DATA_CALC VARCHAR(5) NOT NULL,
	CONSTRAINT pk_performance_disk_date_day_date_hms_data_type PRIMARY KEY(DATE_DAY, DATE_HMS, "DATA_TYPE")
)REUSE_OID;
